### ISSUE TITLE
Send missing headers to auth

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-media-service#11]
In the file `auth.py` the following request is used to authenticate:

```
response = requests.post(check_request_url, headers={"Cookie": cookie})
```
(Extract from [auth.py](https://github.com/OpenSlides/openslides-media-service/blob/0fe5275442250a6e527debb707fb25f75f6aee50/src/auth.py#L11))

I think, the "Authentication"-header has to be set and sent, too, like so:

```
response = requests.post(check_request_url, headers={"Cookie": cookie, "Authentication": access_token})
```

Let me know, if you need more information or other help.

**Comment by FinnStutzenstein** [comment]
@reiterl Can you adjust the mediaservice in the way that

- the header `Authentication` is passed to the presenter service
- If there is an `Authentication` header in the response, it is passed in the response of the media service as well.

**Comment by GabrielInTheWorld** [comment]
I will look into this. There are some information we need, related to [openslides-auth-service#60](https://github.com/OpenSlides/openslides-auth-service/issues/60)
