### ISSUE TITLE
Support resources

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-media-service#13]
In conjunction with https://github.com/OpenSlides/openslides-backend/issues/346 update the mediaservice to implement the updated interface: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/interfaces/media-service.txt

- duplicate the get and update route to upload and retrieve resources. Resources are saved the same way in the database, but must get an own table since mediafile ids and resource ids may overlap.
- For resources, the `check_resource_id` presenter is used.
- Add tests for resources. Since the presenter service is mocked, you can just duplicate all tests and run them once for mediafiles and once for resources

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-media-service/pull/15 for this issue.
