### ISSUE TITLE
Fix mediafiles for public access

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-media-service#136]
**Describe the bug**
A public User cannot see/interact with mediafiles

**How to Reproduce**
1. Upload mediafiles (font, pdf, csv)
2. Activate the mediafile as font, as logo and project a mediafile
3. Create an additional projector and project a motion 
4. Activate the public access for the meeting and give the correstonding group the max amount of permissions
5. Login with a public access
6. Try to see what is projected (it is a black screen)
7. Try downloading a mediafile (A new tab opens)
8. Try seeing the motion with their custom font (the text is gone)

**Expected behavior**
The public access people should be able to see mediafiles and download them if they are activated

**Comment by bastianjoel** [comment]
The mediafile service feature branch was not merged
