### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by danilobuerger** [OpenSlides/openslides-media-service#17]
How can this service be health checked? Currently I check "/" and assume that 404 still means that the service is healthy. This seems weird though.

**Comment by FinnStutzenstein** [comment]
Currently it is not possible I think.

**Comment by danilobuerger** [comment]
@FinnStutzenstein it would be great to make it possible. The use case seems clear to me: when auto scaling in a cloud environment I should be able to determine if a service is healthy or not. The autoupdate service supports this too: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/http/http.go#L32

**Comment by FinnStutzenstein** [comment]
Can you check, if https://github.com/OpenSlides/openslides-media-service/pull/18 works? I currently have not the time to test it.

**Comment by danilobuerger** [comment]
@FinnStutzenstein thanks for the PR! It does work with the modification as mentioned in the PR. Only potential downside could be using a file thats named "health", but I guess in practice thats not going to happen.

**Comment by FinnStutzenstein** [comment]
> Only potential downside could be using a file thats named "health",

Yes, right. I removed the `URL_PREFIX`. This results in no collisions (if the prefix is not `/`) and, at least in our setup, not being routed from the client. So it is not possible to call the health path externally.
