### ISSUE TITLE
Fix entrypoint

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-media-service#40]
The entrypoint (https://github.com/OpenSlides/openslides-media-service/blob/openslides4-dev/entrypoint.sh) contains wrong environment vars. At least the postgres password should be read from secret file. Without this fix the prod setup would be broken.

**Comment by reiterl** [comment]
Which ones?

**Comment by reiterl** [comment]
I have worked at the `entrypoint`( moved it, extract vars, add reading FILE vars). At the moment I think the situation should be okay.

**Comment by normanjaeckel** [comment]
I think https://github.com/OpenSlides/openslides-media-service/blob/openslides4-dev/scripts/entrypoint.sh#L6 is still wrong. The password should be read from secret file and not from env var directly. Please see the correspondent issue in datastore: https://github.com/OpenSlides/openslides-datastore-service/pull/164

**Comment by normanjaeckel** [comment]
See especially https://github.com/jsangmeister/openslides-datastore-service/blob/0847086340c56d737a14fd03cb08a3a9286becae/scripts/system/export-database-variables.sh how the datastore sets `PGPASSWORD` (which is silently used by the `psql` command).

**Comment by jsangmeister** [comment]
The variable is set in https://github.com/OpenSlides/openslides-media-service/blob/openslides4-dev/scripts/service_env.sh. But I agree that this should be done analogous to the datastore (especially should it not be possible to provide the password directly via an env var).

**Comment by jsangmeister** [comment]
also see https://github.com/OpenSlides/openslides-datastore-service/pull/168
